//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rose.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rose.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Uygulama hazırlanıyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string app_initializing {
            get {
                return ResourceManager.GetString("app_initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rose benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dikkat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CAUTION {
            get {
                return ResourceManager.GetString("CAUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HATA! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntü iyileştirme özelliği yalnızca Windows dağıtımında kullanılabilir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string unsupported_os {
            get {
                return ResourceManager.GetString("unsupported_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;user32.dll&apos; bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user32_dll_not_found {
            get {
                return ResourceManager.GetString("user32_dll_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntü iyileştirmeleri uygulanamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string visual_enhancement_error {
            get {
                return ResourceManager.GetString("visual_enhancement_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntü iyileştirmeleri kullanılamayacak. İşletim sistemi sürümü uygun değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string visual_enhancement_error_unvalid_os_version {
            get {
                return ResourceManager.GetString("visual_enhancement_error_unvalid_os_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntü iyileştirmeleri uygulandı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string visual_enhancement_ok {
            get {
                return ResourceManager.GetString("visual_enhancement_ok", resourceCulture);
            }
        }
    }
}
